In [1]:
import pandas as pd

In [2]:
traffic=pd.read_csv('./dataset/traffic.csv').dropna(how='all') ## nan 도배된것 처리후 중간 중간 nan 0처리
links=pd.read_csv('./dataset/Seoul_links_190709.csv').dropna(how='all')
nodes=pd.read_csv('./dataset/Seoul_nodes_190709.csv').dropna(how='all')

In [3]:
del links['Unnamed: 0'],links['REST_VEH'], links['REST_W'],links['REST_H'],links['REMARK'],links['USER_ID'],links['WORKSTATE']
del links['DEPT_CODE'],links['STNL_REG'],links['ROAD_TYPE'],links['ROAD_NO'],links['TMPID'],links['UPLOAD_ID']
del links['SOSFNODEID'],links['SOSTNODEID'],links['SHAPE_STLe'],links['geometry'],links['ROAD_USE'],links['MAX_SPD']

In [4]:
links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT
0,1000045000,1000010900,1000011600,1.0,103,종로,0,103
1,1000044700,1010034900,1000031400,1.0,104,종로40길,0,0
2,1000044800,1000031400,1010034900,1.0,104,종로40길,0,0
3,1000044900,1000031200,1000031300,1.0,103,종로,0,0
4,1000005602,1000031200,1000011000,5.0,107,창경궁로,0,0
...,...,...,...,...,...,...,...,...
20179,1230426500,1230184900,1230185300,2.0,107,법원로5길,0,0
20180,1230426800,1230185000,1230185300,2.0,107,법원로,0,0
20181,1230426900,1230185300,1230185000,2.0,107,법원로,0,0
20182,1230427000,1230185300,1230015800,2.0,107,법원로,0,0
20183,1230427100,1230015800,1230185300,2.0,107,법원로,0,0

In [5]:
nodes
nodes=nodes[['Id','latitude','longitude']]

In [6]:
links = pd.merge(links, nodes, how='left', left_on='Source', right_on='Id')

del links['Id']
links=links.rename(columns = {'latitude':'SourceX', 'longitude':'SourceY'})

In [7]:
links = pd.merge(links, nodes, how='left', left_on='Target', right_on='Id')

del links['Id']
links=links.rename(columns = {'latitude':'TargetX', 'longitude':'TargetY'})

In [8]:
v=pd.read_csv('./rowdataset/2020년 9월 서울시 차량통행속도.csv')

v=v[v['요일']!='일']
v=v[v['요일']!='토']
v=v.rename(columns = { '01시' : 'V01' , '02시' : 'V02', '03시' : 'V03', '04시' : 'V04', '05시' : 'V05', '06시' : 'V06', '07시' : 'V07', '08시' : 'V08', '09시' : 'V09', '10시' : 'V10', '11시' : 'V11', '12시' : 'V12'})
v=v.rename(columns = { '13시' : 'V13' , '14시' : 'V14', '15시' : 'V15', '16시' : 'V16', '17시' : 'V17', '18시' : 'V18', '19시' : 'V19', '20시' : 'V20', '21시' : 'V21', '22시' : 'V22', '23시' : 'V23', '24시' : 'V24'})
v=v[['링크아이디','V01','V02','V03','V04','V05','V06','V07','V08','V09','V10','V11','V12','V13','V14','V15','V16','V17','V18','V19','V20','V21','V22','V23','V24']]

v2=v.groupby('링크아이디').mean()

links = pd.merge(links, v2, how='left', left_on='LINK_ID', right_on='링크아이디')
links=links
links=links[links['V15']!=0]
links=links.dropna(axis = 0, how ='any')

links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,SourceX,SourceY,...,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24
9,1000005800,1010034700,1010005300,2.0,104,청계천로,0,0,37.569629,127.009742,...,20.281364,18.152727,15.651364,14.537727,11.282273,10.050000,12.490000,15.767727,18.818636,19.339091
14,1000003400,1010033700,1010034300,1.0,107,청계천로,0,0,37.569037,126.982780,...,15.884545,15.669091,15.892273,15.663636,10.958182,14.100909,19.010909,20.000000,19.819091,20.447273
40,1000005900,1000011200,1010035000,3.0,104,동호로,0,0,37.571001,127.001926,...,13.131818,13.280455,12.280909,14.684091,17.100455,18.518182,19.559091,21.343182,18.187273,16.439545
41,1000006000,1010035000,1000011200,4.0,104,동호로,0,0,37.569807,127.002020,...,13.329545,12.861818,13.679091,13.589091,13.455000,12.180000,14.469545,18.063182,24.368636,19.013636
90,1000009400,1000015300,1000015500,3.0,107,사직로8길,0,0,37.574071,126.973439,...,22.277727,22.226364,24.208182,25.620000,23.628182,25.190000,24.723636,25.821818,27.026818,26.565000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20093,1230230000,1230117900,1230116200,2.0,107,위례순환로,0,0,37.478171,127.144274,...,16.559545,16.573636,15.746364,16.203636,15.399091,16.299091,18.420455,18.313636,19.605000,19.885000
20107,1230232900,1230117900,1230118300,2.0,107,위례순환로,0,0,37.478171,127.144274,...,17.303636,17.741818,16.511364,14.562727,15.076818,14.804091,16.705000,18.209545,19.391364,19.426818
20108,1230233000,1230118300,1230117900,2.0,107,위례순환로,0,0,37.478091,127.146900,...,14.978182,14.461364,14.563182,14.072273,14.594545,16.584091,15.775000,16.406364,17.409545,19.364091
20109,1230234200,1230118300,1230118700,2.0,107,위례순환로,0,0,37.478091,127.146900,...,16.739091,17.010909,16.004545,14.168182,14.138636,14.060455,15.831364,17.216818,18.290909,18.330455
20110,1230234300,1230118700,1230118300,2.0,107,위례순환로,0,0,37.478030,127.147493,...,15.504545,14.836818,15.031364,14.804091,15.707727,17.242727,16.307273,17.065455,17.704545,19.461364

In [9]:
links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,SourceX,SourceY,...,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24
9,1000005800,1010034700,1010005300,2.0,104,청계천로,0,0,37.569629,127.009742,...,20.281364,18.152727,15.651364,14.537727,11.282273,10.050000,12.490000,15.767727,18.818636,19.339091
14,1000003400,1010033700,1010034300,1.0,107,청계천로,0,0,37.569037,126.982780,...,15.884545,15.669091,15.892273,15.663636,10.958182,14.100909,19.010909,20.000000,19.819091,20.447273
40,1000005900,1000011200,1010035000,3.0,104,동호로,0,0,37.571001,127.001926,...,13.131818,13.280455,12.280909,14.684091,17.100455,18.518182,19.559091,21.343182,18.187273,16.439545
41,1000006000,1010035000,1000011200,4.0,104,동호로,0,0,37.569807,127.002020,...,13.329545,12.861818,13.679091,13.589091,13.455000,12.180000,14.469545,18.063182,24.368636,19.013636
90,1000009400,1000015300,1000015500,3.0,107,사직로8길,0,0,37.574071,126.973439,...,22.277727,22.226364,24.208182,25.620000,23.628182,25.190000,24.723636,25.821818,27.026818,26.565000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20093,1230230000,1230117900,1230116200,2.0,107,위례순환로,0,0,37.478171,127.144274,...,16.559545,16.573636,15.746364,16.203636,15.399091,16.299091,18.420455,18.313636,19.605000,19.885000
20107,1230232900,1230117900,1230118300,2.0,107,위례순환로,0,0,37.478171,127.144274,...,17.303636,17.741818,16.511364,14.562727,15.076818,14.804091,16.705000,18.209545,19.391364,19.426818
20108,1230233000,1230118300,1230117900,2.0,107,위례순환로,0,0,37.478091,127.146900,...,14.978182,14.461364,14.563182,14.072273,14.594545,16.584091,15.775000,16.406364,17.409545,19.364091
20109,1230234200,1230118300,1230118700,2.0,107,위례순환로,0,0,37.478091,127.146900,...,16.739091,17.010909,16.004545,14.168182,14.138636,14.060455,15.831364,17.216818,18.290909,18.330455
20110,1230234300,1230118700,1230118300,2.0,107,위례순환로,0,0,37.478030,127.147493,...,15.504545,14.836818,15.031364,14.804091,15.707727,17.242727,16.307273,17.065455,17.704545,19.461364

In [10]:
traffic=traffic[traffic['요일']!='토']
traffic=traffic[traffic['요일']!='일']

traffic_list=set(traffic['지점명'].tolist())
traffic_list
links_list=set(links['ROAD_NAME'].tolist())
dic={}

links_list

{'4.19로',
 '가락로',
 '가로공원로',
 '가마산로',
 '가산디지털1로',
 '가산디지털2로',
 '가산로',
 '가양대로',
 '가좌로',
 '강남대로',
 '강동대로',
 '강변북로',
 '강변역로',
 '강서로',
 '개포로',
 '거마로',
 '겸재로',
 '경부고속도로',
 '경인로',
 '고산자로',
 '공릉로',
 '광나루로',
 '광나루로56길',
 '구로동로',
 '구로중앙로',
 '구의강변로',
 '구천면로',
 '국회대로',
 '군자로',
 '금낭화로',
 '금하로',
 '금호로',
 '긴고랑로',
 '김포대로',
 '난곡로',
 '남대문로',
 '남대문로7길',
 '남부순환로',
 '내부순환로',
 '노량진로',
 '노원로',
 '노해로',
 '녹사평대로26길',
 '논현로',
 '능동로',
 '다산로',
 '답십리로',
 '당산로',
 '대림로',
 '대방천로',
 '대흥로',
 '덕릉로',
 '덕수궁길',
 '도곡로',
 '도곡로62길',
 '도당로',
 '도림로',
 '도림천로',
 '도봉로',
 '도신로',
 '독막로',
 '독산로',
 '독서당로',
 '돈화문로',
 '돌곶이로',
 '동교로',
 '동남로',
 '동남로12길',
 '동부간선도로',
 '동소문로',
 '동일로',
 '동일로191가길',
 '동일로214길',
 '동작대로',
 '동호로',
 '두텁바위로',
 '디지털로',
 '뚝섬로',
 '마곡중앙5로',
 '마곡중앙로',
 '마들로',
 '마른내로',
 '마장로',
 '마장로1길',
 '마조로',
 '마천로',
 '마포대로',
 '망우로',
 '망우로21길',
 '매봉산로',
 '면목로',
 '면목천로',
 '명달로',
 '목동남로',
 '목동동로',
 '목동로',
 '목동서로',
 '목동중앙로',
 '무교로',
 '무학로',
 '문래로',
 '문정로4길',
 '방배로',
 '방학로',
 '방화동로',
 '백범로',
 '백석동길',
 '버드나루로',
 '범안로',
 '벚꽃로',
 '보광로',
 '보문로',
 '봉우재로',
 '봉은사로',
 '봉천로',
 '봉화산로',
 '부일로',
 '북부간선도로',
 '북촌로',
 '분당수서로',
 '불광로',
 '불광천길',
 '사가정로',
 '사직로',
 '사직로8길',
 '살곶이길',
 '삼각산로',
 '삼선교로',
 '삼성로',
 '삼양로',
 '삼일대로',
 '삼전로',
 '삼청로',
 '삼학사로',
 '상계로',
 '상봉로',
 '새말로',
 '새말로8길',
 '새문안로5길',
 '새창로',
 '서강로',
 '서부간선도로',
 '서빙고로',
 '서빙고로51길',
 '서오릉로',
 '서운로',
 '서울시립대로',
 '서초대로',
 '석촌호수로',
 '선릉로',
 '선유로',
 '선유서로',
 '섬밭로',
 '성미산로',
 '성북로',
 '성수일로',
 '성암로',
 '성중길',
 '세종대로',
 '세종대로20길',
 '소공로',
 '소월로',
 '소월로2길',
 '솔샘로',
 '송이로',
 '송파대로',
 '송파대로60길',
 '수락산로',
 '수명로',
 '수색로',
 '수표로',
 '시흥대로',
 '신길로',
 '신내로',
 '신목로',
 '신목로7길',
 '신사로',
 '신월로',
 '신이문로',
 '신촌로',
 '신풍로',
 '아차산로',
 '아차산로70길',
 '안암로',
 '안양천로',
 '약령시로',
 '양녕로',
 '양산로',
 '양재대로',
 '양재대로55길',
 '양재천로',
 '양천로',
 '양천로27길',
 '양천로55길',
 '양천로57길',
 '양천로59길',
 '양천로61길',
 '양평로',
 '여의대로',
 '여의대방로',
 '여의동로',
 '여의서로',
 '역삼로',
 '연서로',
 '연희로',
 '영동대로',
 '영신로',
 '영중로',
 '오금로',
 '오목로',
 '오패산로',
 '오현로',
 '올림픽대로',
 '올림픽로',
 '올림픽로35길',
 '와우산로',
 '왕산로',
 '왕십리로',
 '용마산로',
 '원효대교진출입로',
 '월계로',
 '월계로21길',
 '월곡로',
 '월드컵로',
 '월드컵북로',
 '위례서로',
 '위례성대로',
 '위례순환로',
 '위례중앙로',
 '율곡로',
 '은평로',
 '을지로',
 '응암로',
 '의사당대로',
 '이태원로',
 '인수봉로',
 '인촌로7길',
 '일반국도6호선',
 '일원로',
 '자곡로',
 '자양로',
 '자양번영로',
 '자유로',
 '잠실로',
 '잠원로',
 '장위로',
 '장충단로',
 '전농로',
 '정동길',
 '정릉로',
 '정릉천동로',
 '제기로',
 '조원중앙로',
 '종로',
 '종로3길',
 '종암로',
 '중계로',
 '중대로',
 '중랑역로',
 '중랑천로',
 '중앙로',
 '증가로',
 '증산로',
 '지봉로',
 '진관2로',
 '진흥로',
 '창의문로',
 '창전로',
 '천호대로',
 '청계천로',
 '청와대로',
 '청파로',
 '초원로',
 '충무로',
 '탄천동로',
 '토정로',
 '통일로',
 '학동로',
 '한가람로',
 '한강대로77길',
 '한글비석로',
 '한남대로',
 '한천로',
 '해등로',
 '허준로',
 '헌릉로',
 '혜화로',
 '홍릉로',
 '홍익로',
 '홍제천로',
 '화곡로',
 '화랑로',
 '회기로',
 '효령로',
 '휘경로',
 '희우정로'}

In [11]:
traffic_list

{'가양대교',
 '강남대로(강남역-신분당)',
 '강남대로(신사역)',
 '강남순환로',
 '강변북로',
 '강변북로(구리시계)',
 '강변북로(난지한강공원)',
 '강서로(화곡터널)',
 '개봉로(개봉교)',
 '경부고속도로',
 '경부고속도로(양재IC)',
 '경인고속국도(신월IC)',
 '경인로(거리공원입구교차로)',
 '경인로(서울교)',
 '경인로(오류IC)',
 '경인로(유한공고)',
 '경춘북로(중랑경찰서)',
 '공항대로(발산역)',
 '과천대로(남태령역)',
 '광명대교(광명시계)',
 '광진교',
 '국회대로(여의2교)',
 '금오로(광명시계)',
 '금천교(광명시계)',
 '금하로(광명시계)',
 '김포대로(개화교)',
 '남부순환로(낙성대역)',
 '남부순환로(수서IC)',
 '남부순환로(신월IC)',
 '남부순환로(예술의전당)',
 '남부순환로(화곡로입구 교차로)',
 '남산1호터널',
 '남산2호터널',
 '남산3호터널',
 '내부순환로',
 '노들로',
 '대사관로(삼청터널)',
 '대학로(한국방송통신대학교)',
 '도봉로(도봉산역)',
 '도봉로(쌍문역)',
 '동부간선도로',
 '동부간선도로(월계1교)',
 '동소문로(길음교사거리)',
 '동일로(군자교)',
 '동일로(노원역)',
 '동일로(의정부IC)',
 '동작대교',
 '동작대로(총신대입구역)',
 '동호대교',
 '동호로(금호터널)',
 '동호로(장충체육관)',
 '뚝섬로(용비교)',
 '마포대교',
 '망우로(망우리공원)',
 '문성로(난곡터널)',
 '반포대교',
 '반포대로(서초역)',
 '반포대로(우면산터널)',
 '밤고개로(세곡동사거리)',
 '백제고분로(종합운동장)',
 '북부간선도로(신내IC)',
 '북부간선로',
 '분당수서로',
 '분당수서로(성남시계)',
 '사직로(사직터널)',
 '사평대로(고속터미널역)',
 '새문안로(서울역사박물관)',
 '서강대교',
 '서부간선도로',
 '서빙고로(한남역)',
 '서소문로(시청역)',
 '서오릉로(고양시계)',
 '서하남로(서하남IC)',
 '성산대교',
 '성산로(금화터널)',
 '성산로(연희IC)',
 '성수대교',
 '세종대로(서울역)',
 '세종대로(시청역2)',
 '소월로(회현역)',
 '소파로(숭의여자대학교)',
 '송파대로(복정역)',
 '송파대로(송파역)',
 '수색로(고양시계)',
 '시흥대로(구로디지털단지역)',
 '시흥대로(석수역)',
 '시흥대로(시흥IC)',
 '신정로(작동터널)',
 '아차산로(워커힐)',
 '양녕로(상도터널)',
 '양재대로(양재IC)',
 '양화대교',
 '언주로(매봉터널)',
 '여의대방로(여의교)',
 '연희로(연희IC)',
 '영동대교',
 '영등포로(오목교)',
 '오리로(광명시계)',
 '오정로(부천시계)',
 '올림픽대교',
 '올림픽대로',
 '올림픽대로(강일IC)',
 '올림픽대로(개화IC)',
 '원효대교',
 '율곡로(안국역)',
 '을지로(을지로3가역)',
 '자하문로(자하문터널)',
 '잠수교',
 '잠실대교',
 '장충단로(장충단공원)',
 '종로(동묘앞역)',
 '종로(종로3가역)',
 '증산로(디지털미디어시티역)',
 '진흥로(구기터널)',
 '창경궁로(서울여자대학교)',
 '천호대교',
 '천호대로(군자교)',
 '천호대로(상일IC)',
 '철산교(광명시계)',
 '청담대교',
 '칠패로(숭례문)',
 '테헤란로(선릉역)',
 '통일로(고양시계)',
 '통일로(산골고개정류장)',
 '퇴계로(신당역)',
 '퇴계로(회현역)',
 '평창문화로(북악터널)',
 '한강대교',
 '한남대교',
 '행주대교',
 '헌릉로(세곡동사거리)',
 '화곡로(화곡로입구)',
 '화랑로(상월곡역)',
 '화랑로(조선왕릉)',
 '화랑로(화랑대역)'}

In [12]:
# 0시 ~ 23시 데이터 추가
links['0시']=0
links['1시']=0
links['2시']=0
links['3시']=0
links['4시']=0
links['5시']=0
links['6시']=0
links['7시']=0
links['8시']=0
links['9시']=0
links['10시']=0
links['11시']=0
links['12시']=0
links['13시']=0
links['14시']=0
links['15시']=0
links['16시']=0
links['17시']=0
links['18시']=0
links['19시']=0
links['20시']=0
links['21시']=0
links['22시']=0
links['23시']=0
links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,SourceX,SourceY,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
9,1000005800,1010034700,1010005300,2.0,104,청계천로,0,0,37.569629,127.009742,...,0,0,0,0,0,0,0,0,0,0
14,1000003400,1010033700,1010034300,1.0,107,청계천로,0,0,37.569037,126.982780,...,0,0,0,0,0,0,0,0,0,0
40,1000005900,1000011200,1010035000,3.0,104,동호로,0,0,37.571001,127.001926,...,0,0,0,0,0,0,0,0,0,0
41,1000006000,1010035000,1000011200,4.0,104,동호로,0,0,37.569807,127.002020,...,0,0,0,0,0,0,0,0,0,0
90,1000009400,1000015300,1000015500,3.0,107,사직로8길,0,0,37.574071,126.973439,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20093,1230230000,1230117900,1230116200,2.0,107,위례순환로,0,0,37.478171,127.144274,...,0,0,0,0,0,0,0,0,0,0
20107,1230232900,1230117900,1230118300,2.0,107,위례순환로,0,0,37.478171,127.144274,...,0,0,0,0,0,0,0,0,0,0
20108,1230233000,1230118300,1230117900,2.0,107,위례순환로,0,0,37.478091,127.146900,...,0,0,0,0,0,0,0,0,0,0
20109,1230234200,1230118300,1230118700,2.0,107,위례순환로,0,0,37.478091,127.146900,...,0,0,0,0,0,0,0,0,0,0
20110,1230234300,1230118700,1230118300,2.0,107,위례순환로,0,0,37.478030,127.147493,...,0,0,0,0,0,0,0,0,0,0

In [13]:
traffic

,일자,요일,지점명,지점번호,방향,구분,0시,1시,2시,3시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
2,20190603,월,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,467.0,306.0,223.0,206.0,...,2002.0,1945.0,1958.0,2184.0,2126.0,1589.0,1406.0,1439.0,1459.0,945.0
3,20190604,화,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,696.0,459.0,327.0,250.0,...,1998.0,2110.0,2164.0,2238.0,2176.0,1662.0,1412.0,1544.0,1428.0,1018.0
4,20190605,수,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,716.0,494.0,360.0,300.0,...,2147.0,2085.0,2280.0,2417.0,2417.0,1949.0,1765.0,1590.0,1517.0,1075.0
5,20190606,목,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,762.0,581.0,512.0,391.0,...,1733.0,1659.0,1661.0,1657.0,1474.0,1198.0,1051.0,1131.0,908.0,699.0
6,20190607,금,성산로(금화터널),A-01,유입,봉원고가차도->독립문역,444.0,322.0,233.0,201.0,...,1997.0,2053.0,2155.0,2219.0,2248.0,1743.0,1386.0,1402.0,1397.0,1152.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8093,20190624,월,서부간선도로,F-09,유출,목동교->신정교,2026.0,1315.0,941.0,904.0,...,2802.0,3046.0,2625.0,2610.0,2598.0,2818.0,3021.0,3143.0,3339.0,3202.0
8094,20190625,화,서부간선도로,F-09,유출,목동교->신정교,2526.0,1563.0,1192.0,1005.0,...,2972.0,2933.0,2716.0,2599.0,2578.0,2866.0,2969.0,3122.0,3146.0,3210.0
8095,20190626,수,서부간선도로,F-09,유출,목동교->신정교,2749.0,1815.0,1249.0,1027.0,...,2968.0,2921.0,2947.0,2741.0,2422.0,2874.0,2781.0,3278.0,3185.0,3129.0
8096,20190627,목,서부간선도로,F-09,유출,목동교->신정교,2698.0,1759.0,1223.0,986.0,...,3034.0,2975.0,2883.0,2704.0,2521.0,2997.0,3008.0,3039.0,3048.0,3194.0
8097,20190628,금,서부간선도로,F-09,유출,목동교->신정교,2810.0,1879.0,1416.0,1111.0,...,2890.0,2643.0,2640.0,2067.0,1760.0,2478.0,2736.0,3111.0,2928.0,3139.0

In [14]:
for i in traffic_list:
    road_name=i[:3]
    if road_name=='종로(': #종로만 예외
        road_name='종로'
    links_weight=links[links['ROAD_NAME'].str.find(road_name)>=0]
    #print(links_weight['ROAD_NAME'])
    #df.loc['서준']['체육'] = 11
    a=traffic[traffic['지점명'].str.find(road_name)>=0]
    weight=a.iloc[:,6:].mean() #ln9,ln10,ln11,ln18,ln19,ln20 sum
    #print(weight)
    #rint(weight)
    dic={**dic,**{ j : weight for j in links_list if road_name in j}}

In [15]:
dic

{'동일로': 0시      630.594595
 1시      479.387387
 2시      370.108108
 3시      320.729730
 4시      387.603604
 5시      786.198198
 6시     1364.090090
 7시     1842.810811
 8시     2022.504505
 9시     1863.207207
 10시    1769.963964
 11시    1683.972973
 12시    1608.081081
 13시    1675.216216
 14시    1776.378378
 15시    1847.288288
 16시    1977.387387
 17시    2116.954955
 18시    2132.819820
 19시    1897.243243
 20시    1531.594595
 21시    1387.072072
 22시    1225.449541
 23시     933.844037
 dtype: float64,
 '동일로191가길': 0시      630.594595
 1시      479.387387
 2시      370.108108
 3시      320.729730
 4시      387.603604
 5시      786.198198
 6시     1364.090090
 7시     1842.810811
 8시     2022.504505
 9시     1863.207207
 10시    1769.963964
 11시    1683.972973
 12시    1608.081081
 13시    1675.216216
 14시    1776.378378
 15시    1847.288288
 16시    1977.387387
 17시    2116.954955
 18시    2132.819820
 19시    1897.243243
 20시    1531.594595
 21시    1387.072072
 22시    1225.449541
 23시     933.844037
 dtype: float64,
 '동일로214길': 0시      630.594595
 1시      479.387387
 2시      370.108108
 3시      320.729730
 4시      387.603604
 5시      786.198198
 6시     1364.090090
 7시     1842.810811
 8시     2022.504505
 9시     1863.207207
 10시    1769.963964
 11시    1683.972973
 12시    1608.081081
 13시    1675.216216
 14시    1776.378378
 15시    1847.288288
 16시    1977.387387
 17시    2116.954955
 18시    2132.819820
 19시    1897.243243
 20시    1531.594595
 21시    1387.072072
 22시    1225.449541
 23시     933.844037
 dtype: float64,
 '도봉로': 0시      495.8125
 1시      386.6250
 2시      314.3375
 3시      288.0875
 4시      360.2125
 5시      604.8625
 6시      992.8000
 7시     1578.9750
 8시     1738.9375
 9시     1445.7500
 10시    1290.3375
 11시    1229.8250
 12시    1161.0750
 13시    1205.1000
 14시    1252.7250
 15시    1276.1375
 16시    1383.0125
 17시    1534.8750
 18시    1638.4625
 19시    1416.2000
 20시    1101.3250
 21시     975.7125
 22시     877.3250
 23시     684.5500
 dtype: float64,
 '올림픽대로': 0시     1591.389262
 1시     1079.771812
 2시      816.006711
 3시      732.489933
 4시     1125.513514
 5시     2841.135135
 6시     4539.993243
 7시     4864.344595
 8시     4788.317568
 9시     4565.310811
 10시    4554.452703
 11시    4461.695946
 12시    4356.087838
 13시    4498.322148
 14시    4540.657718
 15시    4522.920530
 16시    4657.430464
 17시    4768.523179
 18시    4713.337748
 19시    4281.067114
 20시    3884.503356
 21시    3761.429530
 22시    3418.531915
 23시    2570.659574
 dtype: float64,
 '올림픽로35길': 0시     1591.389262
 1시     1079.771812
 2시      816.006711
 3시      732.489933
 4시     1125.513514
 5시     2841.135135
 6시     4539.993243
 7시     4864.344595
 8시     4788.317568
 9시     4565.310811
 10시    4554.452703
 11시    4461.695946
 12시    4356.087838
 13시    4498.322148
 14시    4540.657718
 15시    4522.920530
 16시    4657.430464
 17시    4768.523179
 18시    4713.337748
 19시    4281.067114
 20시    3884.503356
 21시    3761.429530
 22시    3418.531915
 23시    2570.659574
 dtype: float64,
 '올림픽로': 0시     1591.389262
 1시     1079.771812
 2시      816.006711
 3시      732.489933
 4시     1125.513514
 5시     2841.135135
 6시     4539.993243
 7시     4864.344595
 8시     4788.317568
 9시     4565.310811
 10시    4554.452703
 11시    4461.695946
 12시    4356.087838
 13시    4498.322148
 14시    4540.657718
 15시    4522.920530
 16시    4657.430464
 17시    4768.523179
 18시    4713.337748
 19시    4281.067114
 20시    3884.503356
 21시    3761.429530
 22시    3418.531915
 23시    2570.659574
 dtype: float64,
 '강변북로': 0시     2547.522523
 1시     1730.414414
 2시     1260.558559
 3시     1103.459459
 4시     1529.648649
 5시     3598.360360
 6시     5494.495495
 7시     5680.468468
 8시     5657.522523
 9시     5520.036036
 10시    5675.054054
 11시    5665.117117
 12시    5593.891892
 13시    5731.243243
 14시    5712.366972
 15시    5713.935780
 16시    5715.733945
 17시    5494.198198
 18시    5035.432432
 19시    4783.558559
 20시    4911.927928
 21시    5107.558559
 22시    4824.641509
 23시    3879.632075
 dtype: float64,
 '경인로': 0시      627.412500
 1시      449.893750
 2시      318.375000
 3시      254.187500
 4시      355.556250
 5시      797.131250
 6시     1305.618750
 7시     1734.525000
 8시     1735.425000
 9시     1614.593750
 10시    1512.368750
 11시    1477.312500
 12시    1395.100000
 13시    1468.543750
 14시    1501.306250
 15시    1525.312500
 16시    1588.768750
 17시    1680.893750
 18시    1663.806250
 19시    1505.437500
 20시    1337.312500
 21시    1306.700000
 22시    1188.177215
 23시     898.265823
 dtype: float64,
 '소월로': 0시      37.625
 1시      24.775
 2시      18.900
 3시      17.050
 4시      17.600
 5시      47.050
 6시     136.725
 7시     435.075
 8시     595.675
 9시     527.250
 10시    418.800
 11시    442.000
 12시    388.650
 13시    465.950
 14시    481.950
 15시    482.000
 16시    480.775
 17시    505.675
 18시    552.375
 19시    423.500
 20시    263.600
 21시    161.300
 22시    119.250
 23시     83.825
 dtype: float64,
 '소월로2길': 0시      37.625
 1시      24.775
 2시      18.900
 3시      17.050
 4시      17.600
 5시      47.050
 6시     136.725
 7시     435.075
 8시     595.675
 9시     527.250
 10시    418.800
 11시    442.000
 12시    388.650
 13시    465.950
 14시    481.950
 15시    482.000
 16시    480.775
 17시    505.675
 18시    552.375
 19시    423.500
 20시    263.600
 21시    161.300
 22시    119.250
 23시     83.825
 dtype: float64,
 '증산로': 0시      893.600
 1시      657.600
 2시      508.375
 3시      420.825
 4시      542.975
 5시     1117.925
 6시     1562.625
 7시     1699.100
 8시     1718.750
 9시     1772.225
 10시    1702.025
 11시    1607.600
 12시    1574.175
 13시    1639.475
 14시    1666.950
 15시    1750.500
 16시    1842.225
 17시    1864.075
 18시    1755.900
 19시    1617.025
 20시    1558.600
 21시    1615.775
 22시    1549.875
 23시    1296.400
 dtype: float64,
 '서오릉로': 0시      308.250
 1시      211.500
 2시      174.550
 3시      153.725
 4시      208.825
 5시      442.875
 6시      830.900
 7시     1246.050
 8시     1306.475
 9시     1094.650
 10시    1007.350
 11시     999.225
 12시     992.925
 13시    1027.975
 14시    1038.350
 15시    1037.850
 16시    1141.150
 17시    1284.225
 18시    1407.600
 19시    1205.600
 20시     927.500
 21시     774.400
 22시     661.375
 23시     458.125
 dtype: float64,
 '동부간선도로': 0시     2141.849315
 1시     1493.452055
 2시     1116.944444
 3시      981.263889
 4시     1335.763889
 5시     2720.319444
 6시     3324.513889
 7시     3164.430556
 8시     2903.986111
 9시     3004.106667
 10시    3098.753247
 11시    3151.961039
 12시    3226.155844
 13시    3292.721519
 14시    3218.772152
 15시    3265.544304
 16시    3334.898734
 17시    3290.708861
 18시    2960.772152
 19시    2926.782051
 20시    3101.397436
 21시    3255.371795
 22시    3222.148649
 23시    2864.081081
 dtype: float64,
 '동작대로': 0시      880.100000
 1시      598.600000
 2시      422.175000
 3시      326.712500
 4시      392.687500
 5시      897.362500
 6시     1707.812500
 7시     2213.650000
 8시     2300.450000
 9시     2192.300000
 10시    2058.925000
 11시    1956.087500
 12시    1877.312500
 13시    1924.637500
 14시    1995.950000
 15시    2037.250000
 16시    2142.987500
 17시    2155.462500
 18시    2128.312500
 19시    1762.887500
 20시    1611.750000
 21시    1670.975000
 22시    1602.184211
 23시    1283.500000
 dtype: float64,
 '북부간선도로': 0시     1251.014286
 1시      853.428571
 2시      658.600000
 3시      632.257143
 4시      978.442857
 5시     2260.300000
 6시     2921.485714
 7시     3038.100000
 8시     2951.814286
 9시     2982.185714
 10시    2996.385714
 11시    2979.714286
 12시    3004.457143
 13시    3087.528571
 14시    3078.300000
 15시    3075.528571
 16시    3188.242857
 17시    3191.628571
 18시    3051.714286
 19시    2884.414286
 20시    2876.700000
 21시    2809.171429
 22시    2562.909091
 23시    1956.348485
 dtype: float64,
 '천호대로': 0시      763.925000
 1시      557.737500
 2시      437.700000
 3시      372.475000
 4시      458.225000
 5시      989.662500
 6시     1841.462500
 7시     2459.371795
 8시     2714.307692
 9시     2467.576923
 10시    2319.300000
 11시    2192.787500
 12시    2068.612500
 13시    2161.787500
 14시    2260.850000
 15시    2334.862500
 16시    2380.537500
 17시    2483.350000
 18시    2544.900000
 19시    2276.900000
 20시    1870.862500
 21시    1745.637500
 22시    1549.974359
 23시    1158.589744
 dtype: float64,
 '통일로': 0시      733.2875
 1시      528.6750
 2시      378.7750
 3시      317.9625
 4시      448.3250
 5시      915.5500
 6시     1400.4875
 7시     1582.6000
 8시     1550.9750
 9시     1545.4250
 10시    1536.2500
 11시    1485.3500
 12시    1479.4750
 13시    1527.1750
 14시    1536.6750
 15시    1533.7875
 16시    1592.2000
 17시    1640.0500
 18시    1622.3250
 19시    1555.9500
 20시    1455.7125
 21시    1429.7375
 22시    1338.0625
 23시    1048.1625
 dtype: float64,
 '시흥대로': 0시      783.183333
 1시      566.666667
 2시      414.266667
 3시      347.633333
 4시      510.341667
 5시     1227.891667
 6시     1773.916667
 7시     2458.858333
 8시     2438.750000
 9시     2322.508333
 10시    2294.258333
 11시    2164.225000
 12시    2032.491667
 13시    2125.191667
 14시    2213.075000
 15시    2231.241667
 16시    2315.666667
 17시    2511.866667
 18시    2553.200000
 19시    2276.683333
 20시    1859.775000
 21시    1668.266667
 22시    1454.025000
 23시    1127.583333
 dtype: float64,
 '국회대로': 0시      721.000000
 1시      487.736842
 2시      327.918919
 3시      247.921053
 4시      323.500000
 5시      551.270270
 6시     1178.210526
 7시     1862.026316
 8시     2171.552632
 9시     1863.675676
 10시    1640.083333
 11시    1683.166667
 12시    1507.555556
 13시    1688.257143
 14시    1669.971429
 15시    1716.588235
 16시    1787.147059
 17시    1857.416667
 18시    1831.405405
 19시    1577.675676
 20시    1419.131579
 21시    1481.631579
 22시    1407.944444
 23시    1167.305556
 dtype: float64,
 '서부간선도로': 0시     2193.868421
 1시     1480.000000
 2시     1065.894737
 3시      924.552632
 4시     1345.184211
 5시     2575.973684
 6시     2847.473684
 7시     2498.447368
 8시     2153.157895
 9시     2526.184211
 10시    2599.000000
 11시    2653.368421
 12시    2746.447368
 13시    2690.868421
 14시    2593.589744
 15시    2572.631579
 16시    2528.105263
 17시    2375.394737
 18시    2162.236842
 19시    2464.000000
 20시    2673.210526
 21시    2802.315789
 22시    2780.388889
 23시    2820.777778
 dtype: float64,
 '서빙고로51길': 0시     1031.075000
 1시      736.425000
 2시      549.475000
 3시      437.725000
 4시      469.650000
 5시      779.025000
 6시     1514.075000
 7시     2338.825000
 8시     2609.575000
 9시     2496.775000
 10시    2409.300000
 11시    2401.400000
 12시    2288.650000
 13시    2378.450000
 14시    2515.525000
 15시    2625.450000
 16시    2711.200000
 17시    2752.925000
 18시    2708.650000
 19시    2301.975000
 20시    1923.900000
 21시    2022.150000
 22시    1958.631579
 23시    1489.657895
 dtype: float64,
 '서빙고로': 0시     1031.075000
 1시      736.425000
 2시      549.475000
 3시      437.725000
 4시      469.650000
 5시      779.025000
 6시     1514.075000
 7시     2338.825000
 8시     2609.575000
 9시     2496.775000
 10시    2409.300000
 11시    2401.400000
 12시    2288.650000
 13시    2378.450000
 14시    2515.525000
 15시    2625.450000
 16시    2711.200000
 17시    2752.925000
 18시    2708.650000
 19시    2301.975000
 20시    1923.900000
 21시    2022.150000
 22시    1958.631579
 23시    1489.657895
 dtype: float64,
 '화랑로': 0시      684.758333
 1시      501.316667
 2시      386.000000
 3시      350.708333
 4시      471.616667
 5시      960.500000
 6시     1374.566667
 7시     1692.558333
 8시     1809.487395
 9시     1738.848739
 10시    1677.554622
 11시    1616.168067
 12시    1574.033613
 13시    1614.579832
 14시    1618.445378
 15시    1653.907563
 16시    1718.831933
 17시    1810.541667
 18시    1813.916667
 19시    1675.883333
 20시    1429.525000
 21시    1391.258333
 22시    1260.879310
 23시     983.603448
 dtype: float64,
 '영동대로': 0시     1556.325000
 1시     1156.600000
 2시      877.550000
 3시      697.550000
 4시      714.500000
 5시     1311.050000
 6시     2403.650000
 7시     3080.250000
 8시     3323.675000
 9시     3273.500000
 10시    3381.000000
 11시    3520.750000
 12시    3314.700000
 13시    3531.825000
 14시    3551.925000
 15시    3616.250000
 16시    3697.100000
 17시    3772.950000
 18시    3699.150000
 19시    3415.975000
 20시    3040.475000
 21시    3159.175000
 22시    2948.631579
 23시    2207.736842
 dtype: float64,
 '강서로': 0시      522.175
 1시      433.475
 2시      345.375
 3시      286.825
 4시      332.850
 5시      540.775
 6시      803.575
 7시     1070.300
 8시     1016.125
 9시     1071.400
 10시    1004.400
 11시     981.050
 12시     933.375
 13시     979.750
 14시     994.375
 15시    1013.350
 16시    1018.725
 17시    1057.375
 18시    1045.850
 19시    1007.125
 20시     917.050
 21시     930.325
 22시     856.750
 23시     692.200
 dtype: float64,
 '남부순환로': 0시     1196.537975
 1시      910.765823
 2시      703.215190
 3시      599.987342
 4시      746.037975
 5시     1412.702532
 6시     2197.835443
 7시     2839.398734
 8시     2892.094937
 9시     2805.018987
 10시    2670.094937
 11시    2533.012658
 12시    2395.639241
 13시    2556.240506
 14시    2592.727848
 15시    2634.158228
 16시    2732.310127
 17시    2790.810127
 18시    2765.462025
 19시    2565.145570
 20시    2236.221519
 21시    2242.310127
 22시    2131.462025
 23시    1692.297468
 dtype: float64,
 '김포대로': 0시      328.650
 1시      214.700
 2시      160.825
 3시      151.800
 4시      281.575
 5시      728.025
 6시     1366.075
 7시     1791.625
 8시     1739.050
 9시     1600.150
 10시    1298.300
 11시    1157.125
 12시    1103.975
 13시    1131.450
 14시    1180.250
 15시    1226.925
 16시    1333.575
 17시    1664.450
 18시    1803.825
 19시    1384.775
 20시    1049.500
 21시     947.175
 22시     816.275
 23시     579.750
 dtype: float64,
 '원효대교진출입로': 0시      490.700000
 1시      347.075000
 2시      244.350000
 3시      185.100000
 4시      230.900000
 5시      563.300000
 6시     1057.950000
 7시     1825.925000
 8시     2005.275000
 9시     1745.350000
 10시    1635.475000
 11시    1665.700000
 12시    1417.650000
 13시    1598.675000
 14시    1646.125000
 15시    1688.950000
 16시    1708.500000
 17시    1830.550000
 18시    1839.225000
 19시    1411.300000
 20시    1117.175000
 21시    1061.450000
 22시     932.078947
 23시     716.263158
 dtype: float64,
 '가양대로': 0시     1236.131579
 1시      870.131579
 2시      667.210526
 3시      578.526316
 4시      787.105263
 5시     1917.289474
 6시     3004.894737
 7시     2967.921053
 8시     3205.552632
 9시     3224.447368
 10시    3270.105263
 11시    3316.789474
 12시    3201.736842
 13시    3353.605263
 14시    3410.105263
 15시    3411.026316
 16시    3555.263158
 17시    3638.657895
 18시    3527.289474
 19시    3109.921053
 20시    2660.342105
 21시    2680.605263
 22시    2491.416667
 23시    1884.888889
 dtype: float64,
 '경부고속도로': 0시     2619.112500
 1시     1718.487500
 2시     1213.937500
 3시     1053.625000
 4시     1471.425000
 5시     3741.937500
 6시     6256.612500
 7시     5487.962500
 8시     5317.175000
 9시     5127.237500
 10시    4985.237500
 11시    4891.675000
 12시    4778.475000
 13시    4850.962500
 14시    4756.500000
 15시    4838.687500
 16시    4965.175000
 17시    4986.837500
 18시    4760.512500
 19시    4745.425000
 20시    4724.862500
 21시    5426.750000
 22시    5025.815789
 23시    4076.276316
 dtype: float64,
 '헌릉로': 0시      408.850
 1시      246.025
 2시      181.125
 3시      153.950
 4시      216.450
 5시      593.200
 6시     1307.625
 7시     1904.775
 8시     2010.575
 9시     1969.600
 10시    1821.375
 11시    1744.375
 12시    1576.000
 13시    1666.125
 14시    1751.900
 15시    1868.850
 16시    2063.400
 17시    2246.425
 18시    2293.750
 19시    1854.575
 20시    1335.250
 21시    1212.625
 22시    1061.950
 23시     694.650
 dtype: float64,
 '세종대로20길': 0시      569.753425
 1시      388.589041
 2시      271.301370
 3시      195.904110
 4시      262.616438
 5시      511.493151
 6시     1082.661972
 7시     1827.549296
 8시     2225.253521
 9시     2182.549296
 10시    2032.422535
 11시    2102.197183
 12시    1912.197183
 13시    2062.985915
 14시    2074.239437
 15시    1993.356164
 16시    2023.013699
 17시    2092.164384
 18시    2119.712329
 19시    1709.849315
 20시    1449.835616
 21시    1397.657534
 22시    1209.465753
 23시     926.506849
 dtype: float64,
 '세종대로': 0시      569.753425
 1시      388.589041
 2시      271.301370
 3시      195.904110
 4시      262.616438
 5시      511.493151
 6시     1082.661972
 7시     1827.549296
 8시     2225.253521
 9시     2182.549296
 10시    2032.422535
 11시    2102.197183
 12시    1912.197183
 13시    2062.985915
 14시    2074.239437
 15시    1993.356164
 16시    2023.013699
 17시    2092.164384
 18시    2119.712329
 19시    1709.849315
 20시    1449.835616
 21시    1397.657534
 22시    1209.465753
 23시     926.506849
 dtype: float64,
 '새문안로5길': 0시      561.750
 1시      458.450
 2시      353.925
 3시      276.325
 4시      308.725
 5시      503.925
 6시      867.250
 7시     1230.875
 8시     1326.825
 9시     1303.325
 10시    1279.975
 11시    1307.150
 12시    1261.200
 13시    1393.175
 14시    1377.750
 15시    1336.725
 16시    1321.725
 17시    1316.450
 18시    1398.625
 19시    1235.150
 20시    1096.550
 21시    1088.825
 22시     981.700
 23시     787.800
 dtype: float64,
 '녹사평대로26길': 0시     1040.542857
 1시      765.142857
 2시      572.228571
 3시      425.828571
 4시      465.085714
 5시      910.314286
 6시     1855.485714
 7시     2596.428571
 8시     2408.400000
 9시     2396.571429
 10시    2367.142857
 11시    2384.000000
 12시    2293.142857
 13시    2373.600000
 14시    2372.457143
 15시    2418.228571
 16시    2437.657143
 17시    2456.571429
 18시    2432.742857
 19시    2426.685714
 20시    2102.857143
 21시    2194.085714
 22시    2127.485714
 23시    1535.800000
 dtype: float64,
 '마포대로': 0시     1071.974359
 1시      770.974359
 2시      563.256410
 3시      412.256410
 4시      523.358974
 5시      950.846154
 6시     2077.128205
 7시     3416.974359
 8시     3702.461538
 9시     3188.666667
 10시    2946.435897
 11시    3044.846154
 12시    2618.974359
 13시    2954.564103
 14시    2958.820513
 15시    3061.512821
 16시    3173.820513
 17시    3566.358974
 18시    3595.307692
 19시    2723.820513
 20시    2666.974359
 21시    2673.512821
 22시    2417.405405
 23시    1711.297297
 dtype: float64,
 '종로3길': 0시      716.405405
 1시      607.945946
 2시      487.567568
 3시      400.770270
 4시      421.472973
 5시      621.662162
 6시      910.081081
 7시     1206.391892
 8시     1289.432432
 9시     1280.337838
 10시    1273.432432
 11시    1276.648649
 12시    1279.405405
 13시    1289.459459
 14시    1293.918919
 15시    1291.540541
 16시    1286.027027
 17시    1310.189189
 18시    1286.472973
 19시    1239.783784
 20시    1161.824324
 21시    1099.702703
 22시    1053.229730
 23시     875.567568
 dtype: float64,
 '종로': 0시      716.405405
 1시      607.945946
 2시      487.567568
 3시      400.770270
 4시      421.472973
 5시      621.662162
 6시      910.081081
 7시     1206.391892
 8시     1289.432432
 9시     1280.337838
 10시    1273.432432
 11시    1276.648649
 12시    1279.405405
 13시    1289.459459
 14시    1293.918919
 15시    1291.540541
 16시    1286.027027
 17시    1310.189189
 18시    1286.472973
 19시    1239.783784
 20시    1161.824324
 21시    1099.702703
 22시    1053.229730
 23시     875.567568
 dtype: float64,
 '한강대로77길': 0시    NaN
 1시    NaN
 2시    NaN
 3시    NaN
 4시    NaN
 5시    NaN
 6시    NaN
 7시    NaN
 8시    NaN
 9시    NaN
 10시   NaN
 11시   NaN
 12시   NaN
 13시   NaN
 14시   NaN
 15시   NaN
 16시   NaN
 17시   NaN
 18시   NaN
 19시   NaN
 20시   NaN
 21시   NaN
 22시   NaN
 23시   NaN
 dtype: float64,
 '분당수서로': 0시     1251.862500
 1시      834.112500
 2시      622.787500
 3시      526.125000
 4시      684.912500
 5시     1917.387500
 6시     3441.550000
 7시     3589.275000
 8시     3385.537500
 9시     3316.212500
 10시    3322.137500
 11시    3291.125000
 12시    3270.562500
 13시    3251.687500
 14시    3197.550000
 15시    3255.412500
 16시    3361.462500
 17시    3401.175000
 18시    3302.012500
 19시    3124.012500
 20시    2911.712500
 21시    2911.875000
 22시    2670.460526
 23시    2036.736842
 dtype: float64,
 '양재대로55길': 0시     1410.914286
 1시      935.171429
 2시      665.500000
 3시      528.166667
 4시      655.611111
 5시     1638.277778
 6시     3149.388889
 7시     3623.611111
 8시     3376.166667

In [16]:
for i,c in dic.items():
    links.loc[links["ROAD_NAME"]==i,"0시"]=c[0]
    links.loc[links["ROAD_NAME"]==i,"1시"]=c[1]
    links.loc[links["ROAD_NAME"]==i,"2시"]=c[2]
    links.loc[links["ROAD_NAME"]==i,"3시"]=c[3]
    links.loc[links["ROAD_NAME"]==i,"4시"]=c[4]
    links.loc[links["ROAD_NAME"]==i,"5시"]=c[5]
    links.loc[links["ROAD_NAME"]==i,"6시"]=c[6]
    links.loc[links["ROAD_NAME"]==i,"7시"]=c[7]
    links.loc[links["ROAD_NAME"]==i,"8시"]=c[8]
    links.loc[links["ROAD_NAME"]==i,"9시"]=c[9]
    links.loc[links["ROAD_NAME"]==i,"10시"]=c[10]
    links.loc[links["ROAD_NAME"]==i,"11시"]=c[11]
    links.loc[links["ROAD_NAME"]==i,"12시"]=c[12]
    links.loc[links["ROAD_NAME"]==i,"13시"]=c[13]
    links.loc[links["ROAD_NAME"]==i,"14시"]=c[14]
    links.loc[links["ROAD_NAME"]==i,"15시"]=c[15]
    links.loc[links["ROAD_NAME"]==i,"16시"]=c[16]
    links.loc[links["ROAD_NAME"]==i,"17시"]=c[17]
    links.loc[links["ROAD_NAME"]==i,"18시"]=c[18]
    links.loc[links["ROAD_NAME"]==i,"19시"]=c[19]
    links.loc[links["ROAD_NAME"]==i,"20시"]=c[20]
    links.loc[links["ROAD_NAME"]==i,"21시"]=c[21]
    links.loc[links["ROAD_NAME"]==i,"22시"]=c[22]
    links.loc[links["ROAD_NAME"]==i,"23시"]=c[23]
    
links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,SourceX,SourceY,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
9,1000005800,1010034700,1010005300,2.0,104,청계천로,0,0,37.569629,127.009742,...,0.0000,0.00,0.000,0.0000,0.00,0.000,0.000,0.0000,0.0000,0.000
14,1000003400,1010033700,1010034300,1.0,107,청계천로,0,0,37.569037,126.982780,...,0.0000,0.00,0.000,0.0000,0.00,0.000,0.000,0.0000,0.0000,0.000
40,1000005900,1000011200,1010035000,3.0,104,동호로,0,0,37.571001,127.001926,...,1897.6125,1843.25,1820.625,1823.3375,1841.95,1649.125,1458.550,1332.8125,1171.5125,868.575
41,1000006000,1010035000,1000011200,4.0,104,동호로,0,0,37.569807,127.002020,...,1897.6125,1843.25,1820.625,1823.3375,1841.95,1649.125,1458.550,1332.8125,1171.5125,868.575
90,1000009400,1000015300,1000015500,3.0,107,사직로8길,0,0,37.574071,126.973439,...,1952.9500,1989.50,2078.700,2201.7000,2177.25,1857.400,1644.025,1679.8000,1559.2500,1250.525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20093,1230230000,1230117900,1230116200,2.0,107,위례순환로,0,0,37.478171,127.144274,...,0.0000,0.00,0.000,0.0000,0.00,0.000,0.000,0.0000,0.0000,0.000
20107,1230232900,1230117900,1230118300,2.0,107,위례순환로,0,0,37.478171,127.144274,...,0.0000,0.00,0.000,0.0000,0.00,0.000,0.000,0.0000,0.0000,0.000
20108,1230233000,1230118300,1230117900,2.0,107,위례순환로,0,0,37.478091,127.146900,...,0.0000,0.00,0.000,0.0000,0.00,0.000,0.000,0.0000,0.0000,0.000
20109,1230234200,1230118300,1230118700,2.0,107,위례순환로,0,0,37.478091,127.146900,...,0.0000,0.00,0.000,0.0000,0.00,0.000,0.000,0.0000,0.0000,0.000
20110,1230234300,1230118700,1230118300,2.0,107,위례순환로,0,0,37.478030,127.147493,...,0.0000,0.00,0.000,0.0000,0.00,0.000,0.000,0.0000,0.0000,0.000

In [17]:
links=links[links['SourceX']!=0]
links=links[links['SourceY']!=0]
links=links[links['TargetX']!=0]
links=links[links['TargetY']!=0]

links=links[links['19시']!=0]
links=links.reset_index(drop=True)

In [18]:
links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,SourceX,SourceY,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,1000005900,1000011200,1010035000,3.0,104,동호로,0,0,37.571001,127.001926,...,1897.612500,1843.25000,1820.625000,1823.337500,1841.950000,1649.125000,1458.550000,1332.81250,1171.512500,868.575000
1,1000006000,1010035000,1000011200,4.0,104,동호로,0,0,37.569807,127.002020,...,1897.612500,1843.25000,1820.625000,1823.337500,1841.950000,1649.125000,1458.550000,1332.81250,1171.512500,868.575000
2,1000009400,1000015300,1000015500,3.0,107,사직로8길,0,0,37.574071,126.973439,...,1952.950000,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000
3,1000009300,1000015500,1000015300,1.0,107,사직로8길,0,0,37.574106,126.974472,...,1952.950000,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000
4,1000011800,1000019300,1000019800,4.0,103,사직로,1,0,37.575758,126.974331,...,1952.950000,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,1230004800,1230058600,1230053400,4.0,102,올림픽대로,0,0,37.522419,127.100915,...,4540.657718,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574
334,1230030400,1230050300,1230049800,2.0,102,송파대로60길,0,102,37.516405,127.097793,...,1832.037500,1870.41250,1945.487500,2050.312500,2089.875000,1826.275000,1528.787500,1491.17500,1392.725000,1054.887500
335,1230005100,1230054000,1230052500,4.0,102,올림픽대로,0,0,37.527343,127.106555,...,4540.657718,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574
336,1230003900,1230047500,1230046600,4.0,102,올림픽대로,0,0,37.517348,127.088203,...,4540.657718,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574
337,1230004000,1230046000,1230046900,4.0,102,올림픽대로,0,0,37.516830,127.079224,...,4540.657718,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574

In [19]:
onlybus=pd.read_csv('./rowdataset/Row_OnlyBusRoad.csv').dropna(how='all')

In [20]:
#onlybus=onlybus.rename(columns = {'도로명':'OnlyBus'})

In [21]:
onlybus

,구분,운영구분,도로명,기점,종점,기점_위도,기점_경도,종점_위도,종점_경도,거리,방향
0,가로변,전일제,과천대로,남태령전원마을,시계,126.980911,37.466269,126.986059,37.443861,0.9,일방향
1,가로변,전일제,현충로,국립현충원R,한강대교남단,126.969137,37.501065,126.941351,37.517518,1.9,일방향
2,가로변,전일제,노량진로,영등포R,대방역3,126.904940,37.515417,126.924860,37.513121,1.1,양방향
3,가로변,전일제,퇴계로,회현역,광희동4,126.972683,37.557316,126.991349,37.562580,3.0,양방향
4,가로변,전일제,한남로,한남5,한남초교,126.997296,37.549837,127.002807,37.538922,0.6,일방향
...,...,...,...,...,...,...,...,...,...,...,...
77,중앙로,전일제,과천대로,사당역,서울시계,126.933029,37.501587,127.003580,37.511007,2.1,양방향
78,중앙로,전일제,신촌로,신촌R,아현교회,126.940061,37.558038,126.949614,37.558776,1.2,양방향
79,중앙로,전일제,양화로,양화대교,신촌R,126.901509,37.541875,126.940061,37.558038,4.0,양방향
80,중앙로,전일제,새문안로,미동초교,세종로4,126.963117,37.563716,126.976182,37.575774,1.2,양방향
81,중앙로,전일제,종로,세종대로4,동대문R,126.972621,37.558009,127.033043,37.583608,2.8,양방향

In [22]:
Only = links['ROAD_NAME'].isin(onlybus['도로명'])

In [23]:
Only

0      False
1      False
2      False
3      False
4      False
       ...
333    False
334    False
335    False
336    False
337    False
Name: ROAD_NAME, Length: 338, dtype: bool

In [24]:
links['OnlyBus']=Only

In [25]:
links['OnlyBus']=links['OnlyBus'].apply(lambda x: 1 if x==True else 0)
links=links.reset_index(drop=True)
links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,SourceX,SourceY,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,OnlyBus
0,1000005900,1000011200,1010035000,3.0,104,동호로,0,0,37.571001,127.001926,...,1843.25000,1820.625000,1823.337500,1841.950000,1649.125000,1458.550000,1332.81250,1171.512500,868.575000,0
1,1000006000,1010035000,1000011200,4.0,104,동호로,0,0,37.569807,127.002020,...,1843.25000,1820.625000,1823.337500,1841.950000,1649.125000,1458.550000,1332.81250,1171.512500,868.575000,0
2,1000009400,1000015300,1000015500,3.0,107,사직로8길,0,0,37.574071,126.973439,...,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0
3,1000009300,1000015500,1000015300,1.0,107,사직로8길,0,0,37.574106,126.974472,...,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0
4,1000011800,1000019300,1000019800,4.0,103,사직로,1,0,37.575758,126.974331,...,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,1230004800,1230058600,1230053400,4.0,102,올림픽대로,0,0,37.522419,127.100915,...,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0
334,1230030400,1230050300,1230049800,2.0,102,송파대로60길,0,102,37.516405,127.097793,...,1870.41250,1945.487500,2050.312500,2089.875000,1826.275000,1528.787500,1491.17500,1392.725000,1054.887500,0
335,1230005100,1230054000,1230052500,4.0,102,올림픽대로,0,0,37.527343,127.106555,...,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0
336,1230003900,1230047500,1230046600,4.0,102,올림픽대로,0,0,37.517348,127.088203,...,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0
337,1230004000,1230046000,1230046900,4.0,102,올림픽대로,0,0,37.516830,127.079224,...,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0

In [26]:
links.columns

Index(['LINK_ID', 'Source', 'Target', 'LANES', 'ROAD_RANK', 'ROAD_NAME',
       'MULTI_LINK', 'CONNECT', 'SourceX', 'SourceY', 'TargetX', 'TargetY',
       'V01', 'V02', 'V03', 'V04', 'V05', 'V06', 'V07', 'V08', 'V09', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', '0시', '1시', '2시', '3시', '4시', '5시', '6시',
       '7시', '8시', '9시', '10시', '11시', '12시', '13시', '14시', '15시', '16시',
       '17시', '18시', '19시', '20시', '21시', '22시', '23시', 'OnlyBus'],
      dtype='object')

In [27]:
links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,SourceX,SourceY,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,OnlyBus
0,1000005900,1000011200,1010035000,3.0,104,동호로,0,0,37.571001,127.001926,...,1843.25000,1820.625000,1823.337500,1841.950000,1649.125000,1458.550000,1332.81250,1171.512500,868.575000,0
1,1000006000,1010035000,1000011200,4.0,104,동호로,0,0,37.569807,127.002020,...,1843.25000,1820.625000,1823.337500,1841.950000,1649.125000,1458.550000,1332.81250,1171.512500,868.575000,0
2,1000009400,1000015300,1000015500,3.0,107,사직로8길,0,0,37.574071,126.973439,...,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0
3,1000009300,1000015500,1000015300,1.0,107,사직로8길,0,0,37.574106,126.974472,...,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0
4,1000011800,1000019300,1000019800,4.0,103,사직로,1,0,37.575758,126.974331,...,1989.50000,2078.700000,2201.700000,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,1230004800,1230058600,1230053400,4.0,102,올림픽대로,0,0,37.522419,127.100915,...,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0
334,1230030400,1230050300,1230049800,2.0,102,송파대로60길,0,102,37.516405,127.097793,...,1870.41250,1945.487500,2050.312500,2089.875000,1826.275000,1528.787500,1491.17500,1392.725000,1054.887500,0
335,1230005100,1230054000,1230052500,4.0,102,올림픽대로,0,0,37.527343,127.106555,...,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0
336,1230003900,1230047500,1230046600,4.0,102,올림픽대로,0,0,37.517348,127.088203,...,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0
337,1230004000,1230046000,1230046900,4.0,102,올림픽대로,0,0,37.516830,127.079224,...,4522.92053,4657.430464,4768.523179,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0

In [28]:
from sklearn.preprocessing import minmax_scale

links['X'] = (links['SourceX'] + links['TargetX'])/2
links['Y'] = (links['SourceY'] + links['TargetY'])/2

max(links['X']), min(links['X']), max(links['Y']), min(links['Y']) , max(links['X'])- min(links['X']), max(links['Y'])-min(links['Y'])
links['X']=minmax_scale(links['X'], feature_range=(0, 1))
links['Y']=minmax_scale(links['Y'], feature_range=(0, 1))
links['XY']=(links['SourceX']-links['TargetX'])**2+(links['SourceY']-links['TargetY'])**2
links

,LINK_ID,Source,Target,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,SourceX,SourceY,...,18시,19시,20시,21시,22시,23시,OnlyBus,X,Y,XY
0,1000005900,1000011200,1010035000,3.0,104,동호로,0,0,37.571001,127.001926,...,1841.950000,1649.125000,1458.550000,1332.81250,1171.512500,868.575000,0,0.542023,0.612611,0.000001
1,1000006000,1010035000,1000011200,4.0,104,동호로,0,0,37.569807,127.002020,...,1841.950000,1649.125000,1458.550000,1332.81250,1171.512500,868.575000,0,0.542023,0.612611,0.000001
2,1000009400,1000015300,1000015500,3.0,107,사직로8길,0,0,37.574071,126.973439,...,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0,0.559109,0.528297,0.000001
3,1000009300,1000015500,1000015300,1.0,107,사직로8길,0,0,37.574106,126.974472,...,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0,0.559109,0.528297,0.000001
4,1000011800,1000019300,1000019800,4.0,103,사직로,1,0,37.575758,126.974331,...,2177.250000,1857.400000,1644.025000,1679.80000,1559.250000,1250.525000,0,0.567186,0.526877,0.000003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,1230004800,1230058600,1230053400,4.0,102,올림픽대로,0,0,37.522419,127.100915,...,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0,0.330347,0.919239,0.000057
334,1230030400,1230050300,1230049800,2.0,102,송파대로60길,0,102,37.516405,127.097793,...,2089.875000,1826.275000,1528.787500,1491.17500,1392.725000,1054.887500,0,0.299034,0.899092,0.000012
335,1230005100,1230054000,1230052500,4.0,102,올림픽대로,0,0,37.527343,127.106555,...,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0,0.332050,0.918793,0.000052
336,1230003900,1230047500,1230046600,4.0,102,올림픽대로,0,0,37.517348,127.088203,...,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0,0.295128,0.861402,0.000051
337,1230004000,1230046000,1230046900,4.0,102,올림픽대로,0,0,37.516830,127.079224,...,4713.337748,4281.067114,3884.503356,3761.42953,3418.531915,2570.659574,0,0.294086,0.858661,0.000081

In [29]:
links.to_csv('./dataset/수홍velocity.csv')