In [1]:
import geopandas as gpd
import shapefile  #the pyshp module : Should install pyshp module.
import pandas as pd
from pyproj import Proj, transform # Should install pyproj module.

In [2]:
# read data (Copy all files from nodelink into nodelink folder: I made it.)
# using old_data
shp_path_node = './rowdataset/MOCT_NODE.shp'
sf_node = gpd.read_file(shp_path_node,encoding='cp949')
sf_n=shapefile.Reader(shp_path_node)
shp_path_link = './rowdataset/MOCT_LINK.shp'
sf_link = gpd.read_file(shp_path_link,encoding='cp949')

In [3]:
shps = [s.points for s in sf_n.shapes()] # node has coordinate data.
#node
node_dataframe = gpd.GeoDataFrame(sf_node)
#add the coordinate data to a column called "coords"
node_dataframe = node_dataframe.assign(coords=shps)
# link
link_dataframe = gpd.GeoDataFrame(sf_link)

In [4]:
node_dataframe[1:5]

,NODE_ID,NODE_TYPE,NODE_NAME,TURN_P,REMARK,USER_ID,WORKSTATE,DEPT_CODE,STNL_REG,TMPID,UPLOAD_ID,geometry,coords
1,3330016500,104,벌교터널,0,None,korea,5,None,333,OEXT3330016500,None,POINT (229535.218 250194.520),"[[229535.21800000034, 250194.52040000074]]"
2,3330015600,104,벌교터널,0,None,korea,5,None,333,OEXT3330015600,None,POINT (229465.270 249416.523),"[[229465.27020000014, 249416.52300000004]]"
3,3330014900,101,벌교교차로,0,None,korea,5,None,333,OEXT3330014900,None,POINT (229455.641 249249.001),"[[229455.64099999983, 249249.00129999965]]"
4,3330014600,101,벌교교차로,0,None,korea,5,None,333,OEXT3330014600,None,POINT (229412.604 249169.926),"[[229412.60429999977, 249169.92640000023]]"

In [5]:
link_dataframe[1:5]

,LINK_ID,F_NODE,T_NODE,ROAD_USE,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,MAX_SPD,...,DEPT_CODE,STNL_REG,ROAD_TYPE,ROAD_NO,TMPID,UPLOAD_ID,SOSFNODEID,SOSTNODEID,SHAPE_STLe,geometry
1,2650003719,2650001502,2650001503,0,1.0,106,지방도446호선,0,000,50.0,...,42000,265,000,446,None,None,None,None,2456.521198,"LINESTRING (301726.415 591060.693, 301739.129 ..."
2,2650003817,2650001505,2650001504,0,1.0,106,지방도446호선,0,000,50.0,...,42000,265,000,446,None,None,None,None,3899.603075,"LINESTRING (306854.537 590126.016, 306814.315 ..."
3,2650003718,2650001503,2650001504,0,1.0,106,지방도446호선,0,000,50.0,...,42000,265,003,446,None,None,None,None,72.692354,"LINESTRING (303861.526 591088.478, 303865.044 ..."
4,2650003818,2650001504,2650001503,0,1.0,106,지방도446호선,0,000,50.0,...,42000,265,003,446,None,None,None,None,73.238101,"LINESTRING (303923.919 591052.828, 303922.825 ..."

In [6]:
# Data restriction
range_STNL_REG=range(100,124) # STNL_REG for Incheon
df_node = pd.DataFrame()
df_link = pd.DataFrame()
for ii in range_STNL_REG:
    res_node = node_dataframe[node_dataframe['STNL_REG'] == str(ii) ] # STNL_REG is not int.
    res_link = link_dataframe[link_dataframe['STNL_REG'] == str(ii) ]
    df_node = pd.concat([df_node,res_node],ignore_index=True) # marge data
    df_link = pd.concat([df_link,res_link],ignore_index=True)

In [7]:
# Change coordinate system
# korea 2000/central belt 2010 (epsg:5186) to wgs84(epsg:4326)
inProj = Proj(init = 'epsg:5186')
outProj= Proj(init = 'epsg:4326')
latitude = []
longitude= []
for idx,row in df_node.iterrows():
    x,y  = row.coords[0][0],row.coords[0][1]  # korea 2000 좌표계
    nx,ny = transform(inProj,outProj,x,y)     # 새로운 좌표계    
    latitude.append(ny)
    longitude.append(nx)
df_node['latitude'] = latitude
df_node['longitude']= longitude
del df_node['coords'] # delete coords

/opt/conda/lib/python3.8/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/opt/conda/lib/python3.8/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
/opt/conda/lib/python3.8/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/opt/conda/lib/python3.8/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
<ipython-input-7-471509ebea30>:9: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  nx,ny = transform(inProj,outProj,x,y)     # 새로운 좌표계

In [8]:
# Change column name to draw network in Gephi
df_node.rename(columns={'NODE_ID':'Id'},inplace = True)
df_link.rename(columns={'F_NODE':'Source','T_NODE':'Target'},inplace = True)

In [9]:
df_node.to_csv('./dataset/Seoul_nodes_190709.csv') # node list
df_link.to_csv('./dataset/Seoul_links_190709.csv') # edge(=link) list

In [10]:
df_node

,Id,NODE_TYPE,NODE_NAME,TURN_P,REMARK,USER_ID,WORKSTATE,DEPT_CODE,STNL_REG,TMPID,UPLOAD_ID,geometry,latitude,longitude
0,1000029100,101,비봉길-진흥로진입로,1,None,None,5,11110,100,None,None,POINT (196181.150 556538.811),37.608424,126.956750
1,1000017800,101,파크뷰타워,1,None,None,5,11110,100,None,None,POINT (197248.124 552890.125),37.575554,126.968848
2,1000018000,101,적선현대빌딩,1,None,None,5,11110,100,None,None,POINT (197587.417 552862.001),37.575301,126.972689
3,1000007300,101,세종로사거리_태평로_진,0,None,None,5,11110,100,None,None,POINT (197963.994 552227.128),37.569582,126.976953
4,1000007600,101,세종로사거리_일반국도6,0,None,None,5,11110,100,None,None,POINT (197897.617 552286.299),37.570115,126.976202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7457,1230016900,101,올림픽훼밀리타운아파트앞,0,None,geostoryco,5,60170,123,None,geostoryco20180530184123,POINT (210481.764 543163.899),37.487865,127.118519
7458,1230184400,101,힐스테이트사거리,0,None,geostoryco,5,60170,123,TMPID20180518180108,geostoryco20180530184123,POINT (210227.657 542862.093),37.485149,127.115641
7459,1230184900,101,동부지방검찰청,0,None,geostoryco,5,60170,123,TMPID20180518180110,geostoryco20180530184123,POINT (210419.838 542450.007),37.481434,127.117808
7460,1230185000,101,지식산업센터사거리,0,None,geostoryco,5,60170,123,TMPID20180518180109,geostoryco20180530184123,POINT (210560.913 542966.754),37.486088,127.119411
7461,1230185300,101,동부지방법원,0,None,geostoryco,5,60170,123,TMPID20180518180111,geostoryco20180530184123,POINT (210705.974 542622.020),37.482980,127.121046

In [11]:
df_link

,LINK_ID,Source,Target,ROAD_USE,LANES,ROAD_RANK,ROAD_NAME,MULTI_LINK,CONNECT,MAX_SPD,...,DEPT_CODE,STNL_REG,ROAD_TYPE,ROAD_NO,TMPID,UPLOAD_ID,SOSFNODEID,SOSTNODEID,SHAPE_STLe,geometry
0,1000045000,1000010900,1000011600,0,1.0,103,종로,0,103,30.0,...,11110,100,000,6,TMP201410L10196,None,None,None,73.936556,"LINESTRING (199741.745 552356.218, 199794.691 ..."
1,1000044700,1010034900,1000031400,1,1.0,104,종로40길,0,000,60.0,...,11110,100,003,-,TMP201410L10109,None,None,TMP201410N10133,33.051833,"LINESTRING (200591.602 552219.527, 200601.656 ..."
2,1000044800,1000031400,1010034900,0,1.0,104,종로40길,0,000,60.0,...,11110,100,003,-,TMP201410L10110,None,TMP201410N10133,None,33.051737,"LINESTRING (200590.225 552254.663, 200580.171 ..."
3,1000044900,1000031200,1000031300,0,1.0,103,종로,0,000,30.0,...,11110,100,000,6,TMP201410L10111,None,TMP201410N10180,TMP201410N10179,82.135332,"LINESTRING (199813.275 552298.713, 199872.192 ..."
4,1000005602,1000031200,1000011000,1,5.0,107,창경궁로,0,000,60.0,...,11110,100,000,-,None,None,TMP201410N10180,None,57.586025,"LINESTRING (199813.275 552298.713, 199808.910 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20179,1230426500,1230184900,1230185300,0,2.0,107,법원로5길,0,000,30.0,...,60170,123,000,-,TMPID20180518180745,geostoryco20180530184123,TMPID20180518180110,TMPID20180518180111,339.448170,"LINESTRING (210422.252 542444.514, 210543.982 ..."
20180,1230426800,1230185000,1230185300,0,2.0,107,법원로,0,000,30.0,...,60170,123,000,-,TMPID20180518181949,geostoryco20180530184123,TMPID20180518180109,TMPID20180518180111,374.112332,"LINESTRING (210555.364 542964.473, 210700.463 ..."
20181,1230426900,1230185300,1230185000,0,2.0,107,법원로,0,000,30.0,...,60170,123,000,-,TMPID20180518181948,geostoryco20180530184123,TMPID20180518180111,TMPID20180518180109,373.908999,"LINESTRING (210711.484 542624.395, 210566.463 ..."
20182,1230427000,1230185300,1230015800,0,2.0,107,법원로,0,000,30.0,...,60170,123,000,-,TMPID20180518181951,geostoryco20180530184123,TMPID20180518180111,None,171.102158,"LINESTRING (210700.463 542619.645, 210769.554 ..."
20183,1230427100,1230015800,1230185300,0,2.0,107,법원로,0,000,30.0,...,60170,123,000,-,TMPID20180518181950,geostoryco20180530184123,None,TMPID20180518180111,170.997749,"LINESTRING (210780.532 542467.958, 210711.484 ..."